-- Insert sample episodes for all languages
INSERT INTO public.episodes (
  title, 
  description, 
  duration_seconds, 
  published_date, 
  is_featured, 
  is_published, 
  language_code,
  thumbnail_url
) VALUES
-- Serbian episodes
('Putovanje kroz Mediteransku Kuhinju', 
 'Otkrivamo tajne tradicionalnih recepata sa Natalia i gošćom Marijom Petrović, poznatom kuvarkom.', 
 2700, 
 '2025-01-15T00:00:00Z', 
 true, 
 true, 
 'sr',
 '🍝'),

('Žensko Preduzetništvo u Srbiji', 
 'Inspirativni razgovor sa uspešnim preduzetnicama o izazovima i pobedama u poslovnom svetu.', 
 3120, 
 '2025-01-12T00:00:00Z', 
 true, 
 true, 
 'sr',
 '👩‍💼'),

('Wellness i Mentalno Zdravlje', 
 'Dubinski razgovor o važnosti mentalnog zdravlja sa dr Anom Nikolić, poznatom psihologinjom.', 
 2280, 
 '2025-01-08T00:00:00Z', 
 true, 
 true, 
 'sr',
 '🧘‍♀️'),

-- German episodes
('Reise durch die mediterrane Küche', 
 'Wir entdecken die Geheimnisse traditioneller Rezepte mit Natalia und Gast Marija Petrović.', 
 2700, 
 '2025-01-15T00:00:00Z', 
 true, 
 true, 
 'de',
 '🍝'),

('Weiblicher Unternehmergeist in Serbien', 
 'Inspirierende Gespräche mit erfolgreichen Unternehmerinnen über Herausforderungen und Erfolge.', 
 3120, 
 '2025-01-12T00:00:00Z', 
 true, 
 true, 
 'de',
 '👩‍💼'),

('Wellness und psychische Gesundheit', 
 'Ein tiefgründiges Gespräch über die Bedeutung der psychischen Gesundheit mit Dr. Ana Nikolić.', 
 2280, 
 '2025-01-08T00:00:00Z', 
 true, 
 true, 
 'de',
 '🧘‍♀️'),

-- English episodes
('Journey Through Mediterranean Cuisine', 
 'We discover the secrets of traditional recipes with Natalia and guest Marija Petrović.', 
 2700, 
 '2025-01-15T00:00:00Z', 
 true, 
 true, 
 'en',
 '🍝'),

('Women Entrepreneurship in Serbia', 
 'Inspirational conversation with successful entrepreneurs about challenges and victories.', 
 3120, 
 '2025-01-12T00:00:00Z', 
 true, 
 true, 
 'en',
 '👩‍💼'),

('Wellness and Mental Health', 
 'In-depth conversation about the importance of mental health with Dr. Ana Nikolić.', 
 2280, 
 '2025-01-08T00:00:00Z', 
 true, 
 true, 
 'en',
 '🧘‍♀️');